### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by stepinbefore** [TheDevFab/Telegram-Support-Bot#1]
`Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from resources import msg_handler as msg
  File "/home/Telegram-Support-Bot/resources/msg_handler.py", line 97
    channel_id   = re.sub(r"-100(\S+)", r"\1", str(config.support_chat))
             ^
SyntaxError: invalid syntax
`

**Comment by TheDevFab** [comment]
Hi,

I haven't had any time to look into this, yet. Quick question beforehand, did the bot ever work for you?

**Comment by stepinbefore** [comment]
> Hi,
> 
> I haven't had any time to look into this, yet. Quick question beforehand, did the bot ever work for you?

No

**Comment by reduxionist** [comment]
Hi,

I also encountered this issue, it is due to the (uncaught) exception handling opened on line 75 of resources/msg_handler.py. Either the try on that line needs to be removed, or an except clause needs to be added on line 96. I removed it and the bot worked as advertised. I'll submit PRs for both approaches though, and you can merge whichever you prefer @TheDevFab.

**Comment by TheDevFab** [comment]
Awesome, I already had an idea like that in the back of my head just had no time to test it. A PR would be much appreciated. Thank you, reduxionist.

**Comment by reduxionist** [comment]
I think the function's control-flow is thorough enough that the exception handling is unnecessary and so preferred the removal performed in #3, but you may know of other exceptions you encountered during development that require it be kept as in #2.

Thanks for sharing Telegram-Support-Bot!

**Comment by TheDevFab** [comment]
#3 looks indeed the cleanest and I have just merged it. Thanks for the PR, @reduxionist.
